# Generated by Django 6.0.5 on 2026-06-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('tier', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('blacklisted', 'Blacklisted')], default='regular', max_length=20)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'guest'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
